# Generated by Django 6.0.1 on 2026-02-21 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationmember',
            name='temp_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members_temp', to='accounts.role'),
        ),
        migrations.AddField(
            model_name='user',
            name='temp_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_temp', to='accounts.role'),
        ),
    ]
