# Generated by Django 6.0.1 on 2026-02-06 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='usage',
            name='api_calls_used',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usage',
            name='customers_created',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usage',
            name='team_members_added',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='PlanLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('FREE', 'Free'), ('BASIC', 'Basic'), ('PRO', 'Pro')], max_length=20)),
                ('feature', models.CharField(choices=[('invoices', 'Invoices'), ('customers', 'Customers'), ('team_members', 'Team Members'), ('api_calls', 'API Calls/month'), ('reports', 'Advanced Reports')], max_length=50)),
                ('limit_value', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Plan Limits',
                'unique_together': {('plan', 'feature')},
            },
        ),
    ]
