# Generated by Django 6.0.1 on 2026-03-02 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_payment_delete_invoicepayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='lead_status',
            field=models.CharField(choices=[('LEAD', 'Lead'), ('INTERESTED', 'Interested'), ('CUSTOMER', 'Customer')], default='LEAD', max_length=20),
        ),
    ]
