# Generated by Django 6.0.1 on 2026-03-06 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_customer_lead_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='lead_status',
        ),
    ]
