# Generated by Django 6.0.1 on 2026-03-10 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_organization_logo_organization_vat_number'),
        ('hr', '0004_leaverequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('basic_salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('working_days', models.IntegerField(default=30)),
                ('present_days', models.IntegerField(default=0)),
                ('absent_days', models.IntegerField(default=0)),
                ('leave_days', models.IntegerField(default=0)),
                ('half_days', models.IntegerField(default=0)),
                ('allowances', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('deductions', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('absence_deduction', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('net_salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('FINALIZED', 'Finalized'), ('PAID', 'Paid')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to='hr.employee')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to='core.organization')),
            ],
            options={
                'ordering': ['-month', 'employee__full_name'],
                'unique_together': {('organization', 'employee', 'month')},
            },
        ),
    ]
