# Generated by Django 6.0.1 on 2026-02-26 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='org_logos/'),
        ),
        migrations.AddField(
            model_name='organization',
            name='vat_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
