# Generated by Django 6.0.1 on 2026-03-17 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('slot_duration_minutes', models.PositiveIntegerField(default=30)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='appointments.staff')),
            ],
            options={
                'verbose_name_plural': 'Staff Availabilities',
                'unique_together': {('staff', 'day_of_week', 'start_time', 'end_time')},
            },
        ),
    ]
